# Generated by Django 5.2.1 on 2025-05-26 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_searchcollection_savedsearch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchcollection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='searchcollection',
            name='user',
        ),
        migrations.AddField(
            model_name='userplan',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='userplan',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='subscription_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SavedSearch',
        ),
        migrations.DeleteModel(
            name='SearchCollection',
        ),
    ]
